#!/bin/sh
#
# xconfig-video_enable="YES"
#

# PROVIDE: xconfig
# REQUIRE: LOGIN cleanvar moused syscons dbus
# BEFORE: gdm kdm lightdm pcdm sddm slim xdm

. /etc/rc.subr

name=xconfig
rcvar=xconfig_enable

command="/usr/local/bin/xconfig service"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
