#!/bin/sh
#####################################################################
# Copyright (c) 2012, Eric Turgeon. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistribution's of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistribution's in binary form must reproduce the above
#    copyright notice,this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#
# 3. Neither then name of  Eric Turgeon nor the names of its
#    contributors maybe used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES(INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#####################################################################

CONF=${CONF:-conf/ghostbsd.defaults.conf}
# Start whit i386.
sed -i '' 's@ARCH="amd64"@ARCH="i386"@' ${CONF}

# Build for LXDE i386.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"mate"}@PACK_PROFILE=${PACK_PROFILE:-"lxde"}@' ${CONF}
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"openbox"}@PACK_PROFILE=${PACK_PROFILE:-"lxde"}@' ${CONF}
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"xfce4"}@PACK_PROFILE=${PACK_PROFILE:-"lxde"}@' ${CONF}
make clean cleandir
make
make img

# Build for Mate i386.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"lxde"}@PACK_PROFILE=${PACK_PROFILE:-"mate"}@' ${CONF}
make clean cleandir
make
make img

# Build for Xfce4 i386.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"mate"}@PACK_PROFILE=${PACK_PROFILE:-"xfce4"}@' ${CONF}
make clean cleandir
make
make img

# Build for Openbox i386.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"xfce4"}@PACK_PROFILE=${PACK_PROFILE:-"openbox"}@' ${CONF}
make clean cleandir
make
make img

# Change to amd64.
sed -i '' 's@ARCH="i386"@ARCH="amd64"@' ${CONF}

# Build for Lxde amd64.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"openbox"}@PACK_PROFILE=${PACK_PROFILE:-"lxde"}@' ${CONF}
make clean cleandir
make
make img

# Build for Mate amd64.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"lxde"}@PACK_PROFILE=${PACK_PROFILE:-"mate"}@' ${CONF}
make clean cleandir
make
make img

# Build for Xfce4 amd64.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"mate"}@PACK_PROFILE=${PACK_PROFILE:-"xfce4"}@' ${CONF}
make clean cleandir
make
make img

# Build for Openbox amd64.
sed -i '' 's@PACK_PROFILE=${PACK_PROFILE:-"xfce4"}@PACK_PROFILE=${PACK_PROFILE:-"openbox"}@' ${CONF}
make clean cleandir
make
make img
