#!/bin/sh
#
# Wrapper to include configuration variables and invoke correct scripts
#
# $FreeBSD$

set -e -u

if [ "`id -u`" != "0" ]; then
    echo "Sorry, this must be done as root."
    exit 1
fi

curdir=`pwd`

PACK_PROFILE=cinnamon
export PACK_PROFILE

ARCH=i386
export ARCH

. ./../conf/ghostbsd.defaults.conf
. ./../scripts/functions.sh

stop_jail
stop_dev
cd $curdir && cd .. && make cleandir

MAKEOBJDIRPREFIX=/usr/obj/gblogs/${ARCH}/${PACK_PROFILE}
rm -Rf $(find $MAKEOBJDIRPREFIX -type d -name $(pwd | rev | cut -d / -f 2,2 | rev))
