#!/bin/sh
#
# Wrapper to include configuration variables and invoke correct scripts
#
# $FreeBSD$

set -e -u

if [ "`id -u`" != "0" ]; then
    echo "Sorry, this must be done as root."
    exit 1
fi

curdir=`pwd`

PACK_PROFILE=mini
export PACK_PROFILE

ARCH=amd64
export ARCH

MAKEOBJDIRPREFIX=/usr/obj/gblogs/$ARCH/$PACK_PROFILE
export MAKEOBJDIRPREFIX

cd $curdir && cd .. && make iso
