#!/bin/sh
#
# Wrapper to include configuration variables and invoke correct scripts
#
# $FreeBSD$

set -e -u

if [ "`id -u`" != "0" ]; then
    echo "Sorry, this must be done as root."
    exit 1
fi

curdir=`pwd`

PACK_PROFILE=gnome
export PACK_PROFILE

ARCH=amd64
export ARCH

USR_SIZE=5.6
export USR_SIZE

INSTALL_PORTS=${INSTALL_PORTS:-"audio/lame"}
export INSTALL_PORTS

EXTRA="common-live-setting common-base-setting gitpkg adduser finalize"
export EXTRA

MAKEOBJDIRPREFIX=/usr/obj/gblogs/${ARCH}/${PACK_PROFILE}
export MAKEOBJDIRPREFIX

cd $curdir && cd .. && make iso
