#!/bin/sh

# Defaults for gnome desktop

# specify GDM3 theme color to be used 
#GNOME_GDM_THEME_COLOR="#000000"

USER=ghostbsd
SMEDIA=live

# Specify WALLPAPER
WALLPAPER="/usr/local/share/pixmaps/backgrounds/gnome/background-default"

# Choose for gnome wallpaper resolution $res instead of 1600x1200 
#res="1920x1200"
#wallpaper_dir="${WALLPAPER}/contents/images/"
#wallpaper_res="${wallpaper_dir}${res}.png"

# Sets FLL_WALLPAPER and GNOME_GDM_BACKGROUND
GHOST_WALLPAPER="${WALLPAPER}.jpg"
GNOME_GDM_BACKGROUND="${GHOST_WALLPAPER}"

# try auto resolution detection
#AUTODETECT_RESOLUTION="true"

# Chose installed default browser
INST_BROWSER="firefox"

# Chose installed default mailer
INST_MAILER="evolution"

# Gnome GDM3 background rendering image option
GNOME_GDM_BACKGROUND_OPTION="stretched"

# Gnome desktop background rendering image option
GNOME_BKG_RENDERING_OPTION="zoom"

# Gnome desktop interface theme
GNOME_GTK_THEME="BlackMATE"

# Gnome desktop icons theme
GNOME_ICON_THEME="brave-dark"

# Gnome desktop metacity theme
GNOME_METACITY_THEME="BlackMATE"

# Gnome fonts rendering image option
GNOME_FONT_RENDERING="slight"

# Gnome terminal disabled F10 key
GNOME_F10_KEY="false"

#Gnome screensaver  autolock remove
GNOME_SCREENSAVER_AUTOLOCK="false"
GNOME_SCREENSAVER_IDLE="false"

#All Gnome's menus to have icons
GNOME_MENUS_HAVE_ICONS="true"

# Gnome OSD section if installed
GNOME_OSD_AVOID_PANELS="true"
GNOME_OSD_ANIMATIONS="true"
GNOME_OSD_DROP_SHADOWS="true"
GNOME_OSD_HALIGNMENT="center"
GNOME_OSD_VPOSITION="top"
GNOME_OSD_PIDGIN_ENABLED="true"
GNOME_OSD_XCHAT_ENABLED="true"

# GNOME sounds if installed
GNOME_ESOUND_ENABLE="true"
GNOME_SOUND_EVENTS_ENABLE="true"

# Nautilus settings
NAUTILUS_ALWAYS_USE_BROWSER="true"
NAUTILUS_ICONS_ZOOM_LEVEL="standard"

# Totem settings
AUTOLOAD_SUBTITLES="true"
AUTOLOAD_CHAPTERS="true"

# GhostBSD Desktop launchers
# On Desktop will remain only not common launcher/launchers from
# GHOSTBSD_DESKTOP_LAUNCHERS and GhostBSD__LAUNCHERS
#GHOSTBSD_DESKTOP_LAUNCHERS="dan-manual dan-irc install-gui"
#GHOSTBSD_LAUNCHERS="GBI"

# Panel Launchers settings
#GHOSTBSD_LAUNCHERS="dan-manual dan-irc"
#OTHER_LAUNCHERS="gnome-terminal pidgin"
#APPLETS_LAUNCHERS="gnome-volume-control"

# GDM3 greeter theme settings
#ALL_USERS_VISIBLE="false"
#COMPOSITE_ENABLE="false"

# Menu Launchers settings format ("Submenu_name1#launcher_name1#launcher_option1, ..........,")
# Beware must be , even before last "
SUBMENU="Accessories#file-roller#Include, Graphics#eog#Include, Graphics#evince#Include, System#GBI#Include, System#bxpkg#Exclude," 


