#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:

if [ -s /usr/local/etc/default/gnome-desktop-settings ]; then
        . /usr/local/etc/default/gnome-desktop-settings
fi

set_polkit_and_root_options()
{
###
# enable polkit operations for users in sudo group
###
polkitdir="/var/lib/polkit-1/localauthority/10-vendor.d"
if [ ! -d "${polkitdir}" ] ; then
        mkdir -p ${polkitdir}
fi

cat > ${polkitdir}/10-live-cd.pkla << EOF
[Live CD user permissions]
Identity=unix-group:wheel
Action=*
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF

cat > ${polkitdir}/com.ghostbsd.desktop.pkla << EOF
[Mounting, checking, etc. of internal drives]
Identity=unix-group:wheel
Action=org.freedesktop.udisks.filesystem-*;org.freedesktop.udisks.drive-ata-smar
t*
ResultActive=yes

[Change CPU Frequency scaling]
Identity=unix-group:wheel
Action=org.gnome.cpufreqselector
ResultActive=yes

[Setting the clock]
Identity=unix-group:wheel
Action=org.gnome.clockapplet.mechanism.*
ResultActive=yes

[Adding or modifying users]
Identity=unix-group:wheel
Action=org.freedesktop.systemtoolsbackends.set
ResultActive=yes

[Live CD user permissions]
Identity=unix-group:wheel
Action=*
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF

###
# disable F10 shortcut key in gnome-terminal for root user
# probably should be verifed also if exists metacity
###
/usr/local/bin/gconftool-2 -s /apps/gnome-terminal/global/use_menu_accelerators -t boolean "false"
}

set_polkit_and_root_options
su $USER -c /usr/local/etc/default/gnome-settings

