#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:

HOME="/home/${USER}"
NAME="gnome-desktop-settings"

if [ -s /usr/local/etc/default/gnome-desktop-settings ]; then
	. /usr/local/etc/default/gnome-desktop-settings
fi

###
# gksu -> sudo
###
if which gconftool-2 >/dev/null; then
	gconftool-2 -s -t bool /apps/gksu/sudo-mode true
	gconftool-2 -s -t bool /apps/gksu/display-no-pass-info false
fi

###
# configure GnuPG if installed
###
GNUPG_CONF="${HOME}/.gnupg/gpg.conf"
KEY_SERVER='hkp://keyserver.noreply.org:80'
if [ ! -f "${GNUPG_CONF}" ]; then
	if which gpg >/dev/null; then
		gpg -k >/dev/null 2>&1
		if [ -f "${GNUPG_CONF}" ]; then
            		sed -ri "" -e 's/^#.*keyserver-options auto-key-retrieve/keyserver-options auto-key-retrieve/' \
		    		-e 's/^#.*charset utf-8/charset utf-8/' \
		    		-e 's/^keyserver /#keyserver/' "${GNUPG_CONF}"
			echo "keyserver ${KEY_SERVER}" >> "${GNUPG_CONF}"
			if which gpg-agent >/dev/null; then
				sed -ri "" 's/^#.*use-agent/use-agent/' "${GNUPG_CONF}"
			fi
		fi
	fi
fi

###
## Make user Desktop dir if doesn't exists
###
if [ ! -d "${HOME}/Desktop" ] ; then
	mkdir -p "${HOME}/Desktop"
fi

ghostbsd_desktop_icons()
{
###
## put a GhostBSD-irc icon on the desktop
####
if [ ! -f "${HOME}/Desktop/ghostbsd-irc.desktop" ] && \
	[ -f /usr/local/share/applications/ghostbsd-irc.desktop ]; then
	ln -s /usr/local/share/applications/ghostbsd-irc.desktop "${HOME}/Desktop/ghostbsd-irc.desktop"
fi

###
## put a installer (GBI icon) on the desktop
####

if [ ! -f "${HOME}/Desktop/GBI.desktop" ] && \
	[ -f /usr/local/share/applications/GBI.desktop ]; then
	cp /usr/local/share/applications/GBI.desktop "${HOME}/Desktop"
	sudo chown ${USER} "${HOME}/Desktop/GBI.desktop"
	sudo chmod 755 "${HOME}/Desktop/GBI.desktop"
fi
}

ghostbsd_cursor_theme()
{
if [ -e /usr/local/lib/X11/icons/default ] ; then
rm /usr/local/lib/X11/icons/default 
fi
ln -s /usr/local/lib/X11/icons/$CURSOR_THEME /usr/local/lib/X11/icons/default 
}

if [ "$SMEDIA" = "live" ] ; then
ghostbsd_desktop_icons
fi

####################
# SETTINGS SECTION #
####################

###
# set wallpaper defaults
###
if [ "${GHOST_WALLPAPER}" ] ; then
# sets for gnome background
gconftool-2 -t string -s /desktop/gnome/background/picture_options ${GNOME_BKG_RENDERING_OPTION}
gconftool-2 -t string -s /desktop/gnome/background/picture_filename  ${GHOST_WALLPAPER}
fi

###
# set theme
###
#if [ -d "/usr/local/share/themes/GhostBSD" ] ; then
gconftool-2 -t string -s /desktop/gnome/interface/gtk_theme  ${GNOME_GTK_THEME}
gconftool-2 -t string -s /desktop/gnome/interface/icon_theme  ${GNOME_ICON_THEME}
gconftool-2 -t string -s /apps/metacity/general/theme  ${GNOME_METACITY_THEME}
#fi

###
# set font_rendering"
###
gconftool-2 -s /desktop/gnome/font_rendering/hinting -t string ${GNOME_FONT_RENDERING}

###
# disable F10 shortcut key in gnome terminal for ${FLL_LIVE_USER}
###
gconftool-2 -s /apps/gnome-terminal/global/use_menu_accelerators -t boolean ${GNOME_F10_KEY}

###
# set remove autolock screensaver
###
gconftool-2 -s /apps/gnome-screensaver/lock_enabled -t boolean ${GNOME_SCREENSAVER_AUTOLOCK}
gconftool-2 -s /apps/gnome-screensaver/idle_activation_enabled -t boolean ${GNOME_SCREENSAVER_IDLE}

###
#  set icons for main menus
###
gconftool-2 -s /desktop/gnome/interface/menus_have_icons -t boolean  ${GNOME_MENUS_HAVE_ICONS}

###
#  set keyboard layout
###
if [ "${XKBLAYOUT}" ] ; then
gconftool-2 -s /desktop/gnome/peripherals/keyboard/kbd/layouts -t string "${XKBLAYOUT}"
gconftool-2 -s /desktop/gnome/peripherals/keyboard/kbd/model -t string "pc104"
#gconftool-2 -s /desktop/gnome/peripherals/keyboard/kbd/options -t string "wellsee"
fi

# unused panels code because it's a matter of preferences
#gconftool-2 --set "/apps/panel/toplevels/bottom_panel_screen0/background/opacity" --type int 45000
#gconftool-2 --set "/apps/panel/toplevels/top_panel_screen0/background/opacity" --type int 45000
#gconftool-2 --set "/apps/panel/toplevels/bottom_panel_screen0/background/type" --type string "color"
#gconftool-2 --set "/apps/panel/toplevels/top_panel_screen0/background/type" --type string "color"

###
# osd if it's installed
###
gconftool-2 --set "/apps/gnome-osd/avoid_panels" --type bool ${GNOME_OSD_AVOID_PANELS}
gconftool-2 --set "/apps/gnome-osd/animations" --type bool ${GNOME_OSD_ANIMATIONS}
gconftool-2 --set "/apps/gnome-osd/drop_shadow" --type bool ${GNOME_OSD_DROP_SHADOWS}
gconftool-2 --set "/apps/gnome-osd/osd_halignment" --type string  ${GNOME_OSD_HALIGNMENT}
gconftool-2 --set "/apps/gnome-osd/osd_vposition" --type string ${GNOME_OSD_VPOSITION}
gconftool-2 --set "/apps/gnome-osd/plugins/pidgin/enabled" --type bool ${GNOME_OSD_PIDGIN_ENABLED}
gconftool-2 --set "/apps/gnome-osd/plugins/xchat/enabled" --type bool ${GNOME_OSD_XCHAT_ENABLED}

###
# sound if it's installed
###
gconftool-2 --set "/desktop/gnome/sound/enable_esd" --type bool ${GNOME_ESOUND_ENABLE}
gconftool-2 --set "/desktop/gnome/sound/event_sounds" --type bool ${GNOME_SOUND_EVENTS_ENABLE}

###
# nautilus settings
###
gconftool-2 --set "/apps/nautilus/preferences/always_use_browser" --type bool ${NAUTILUS_ALWAYS_USE_BROWSER}
gconftool-2 --set "/apps/nautilus/icon_view/default_zoom_level" --type string ${NAUTILUS_ICONS_ZOOM_LEVEL}

###
# totem settings
###
gconftool-2 --set "/apps/totem/autoload_subtitles" --type bool ${AUTOLOAD_SUBTITLES}
gconftool-2 --set "/apps/totem/autoload_chapters" --type bool ${AUTOLOAD_CHAPTERS}

##########################
# MENU LAUNCHERS SECTION #
##########################

add_submenu_entries()
# pass to add_menu_entry desired paramethers after parsing settings file
{
i="0"
howmany=`fgrep SUBMENU= /usr/local/etc/default/${NAME} | awk -F, '{print NF-1}'`

while [ "${i}" -lt "${howmany}" ]
do
i=`expr ${i} + 1`
launcher_info=`fgrep SUBMENU= /usr/local/etc/default/${NAME} | cut -d ',' -f$i| cut -d '"' -f2`
submenu=`echo $launcher_info | cut -d "#" -f1`
launcher=`echo $launcher_info | cut -d "#" -f2`
action=`echo $launcher_info | cut -d "#"  -f3`
add_menu_entry
done
}

add_menu_entry()
{
# test if launcher exists
if [ -f /usr/local/share/applications/$launcher.desktop ] ; then
# makes ./local/share/applications dir to copy launchers there 
	appsdir="${HOME}/.local/share/applications"
		if [ ! -d "${appsdir}" ]; then
			mkdir -p $appsdir
		fi
# edit lauchers with NoDisplay=true and replace it with NoDisplay=false
	gethide=`fgrep "NoDisplay=" /usr/local/share/applications/$launcher.desktop `
	if [ "${gethide}" = "NoDisplay=true" ]; then
		cp /usr/local/share/applications/$launcher.desktop $appsdir/
		chmod 666 $appsdir/$launcher.desktop
	sed -i "" "s@${gethide}@NoDisplay=false@" $appsdir/$launcher.desktop
	fi
fi
# add launcher entry in  ${menudir}/gnome-applications.menu
cat >> ${menudir}/gnome-applications.menu << EOF
		<Menu>
			<Name>${submenu}</Name>
			<${action}>
				<Filename>${launcher}.desktop</Filename> 
			</${action}>
		</Menu>
		
EOF
}

make_menu_entry()
{
menudir="/home/${USER}/.config/menus"
	if [ ! -d "${menudir}" ] ; then
		mkdir -p ${menudir}
	fi
# makes ${menudir}/gnome-applications.menu header
cat > ${menudir}/gnome-applications.menu << EOF
<!DOCTYPE Menu
  PUBLIC '-//freedesktop//DTD Menu 1.0//EN'
  'http://standards.freedesktop.org/menu-spec/menu-1.0.dtd'>
<Menu>
	<Name>Applications</Name>
	<MergeFile type="parent">/usr/local/etc/xdg/menus/gnome-applications.menu</MergeFile>
EOF

# add launchers in submenus
add_submenu_entries

# makes ${menudir}/gnome-applications.menu footer
cat >> ${menudir}/gnome-applications.menu << EOF
		<AppDir>/home/ghostbsd/.local/share/applications</AppDir>
</Menu>
EOF

# makes ${menudir}/gnome-settings.menu file
cat > ${menudir}/gnome-settings.menu << EOF
<!DOCTYPE Menu
  PUBLIC '-//freedesktop//DTD Menu 1.0//EN'
  'http://standards.freedesktop.org/menu-spec/menu-1.0.dtd'>
<Menu>
	<Name>Desktop</Name>
	<MergeFile type="parent">/usr/local/etc/xdg/menus/gnome-settings.menu</MergeFile>
</Menu>
EOF
}

###
# Add all changes to Applications menu at the and END OF MENU LAUNCHERS
###
make_menu_entry

###########################
# PANEL LAUNCHERS SECTION #
###########################

add_launcher()
{
# That's tjtag's ideea and an excellent one
panel="top_panel"
position="${pos}"
right_stick="${right_position}"
locked="${locked_status}"
launcher_path="${launcher}.desktop"
launcher_id="${launcher}_launcher"

# Tweak things
gconftool-2 --set /apps/panel/objects/$launcher_id/object_type -t string launcher-object
gconftool-2 --set /apps/panel/objects/$launcher_id/launcher_location -t string $launcher_path
gconftool-2 --set /apps/panel/objects/$launcher_id/toplevel_id -t string $panel
gconftool-2 --set /apps/panel/objects/$launcher_id/position -t int $position
gconftool-2 --set /apps/panel/objects/$launcher_id/panel_right_stick -t bool $right_stick
gconftool-2 --set /apps/panel/objects/$launcher_id/locked -t bool $locked
object_id_list=$(gconftool-2 --get /apps/panel/general/object_id_list | sed -e "s|]|,$launcher_id]|")

# Finally, add the applet once everything has been setup
gconftool-2 --set /apps/panel/general/object_id_list --type list --list-type string $object_id_list
}

add_applet_launcher()
{
# That's tjtag's ideea and an excellent one
panel="top_panel"
position="${pos}"
right_stick="${right_position}"
locked="${locked_status}"
launcher_path="OAFIID:GNOME_${launcher}"
launcher_id="${launcher}_launcher"

# Tweak things
gconftool-2 --set /apps/panel/applets/$launcher_id/object_type -t string bonobo-applet
gconftool-2 --set /apps/panel/applets/$launcher_id/bonobo_iid -t string $launcher_path
gconftool-2 --set /apps/panel/applets/$launcher_id/panel_id -t string $panel
gconftool-2 --set /apps/panel/applets/$launcher_id/position -t int $position
gconftool-2 --set /apps/panel/applets/$launcher_id/panel_right_stick -t bool $right_stick
gconftool-2 --set /apps/panel/applets/$launcher_id/locked -t bool $locked
object_id_list=$(gconftool-2 --get /apps/panel/applets/object_id_list | sed -e "s|]|,$launcher_id]|")

# Finally, add the applet once everything has been setup
gconftool-2 --set /apps/panel/applets/object_id_list --type list --list-type string $object_id_list
}

add_any_launcher()
{
# finds next available position in panel
# offset it's nedded to make distinction betweeen left and right alignment in panel
	how_many=`gconftool-2 --all-dirs /apps/panel/objects | grep launcher | wc -l`
	start_pos=` expr ${how_many} + ${offset} `
 	pos=` expr ${start_pos} + 1 `
# add launcher
	add_launcher  "${launcher}" 
}

###
# chose installed browser from chrome firefox3 epiphany midori
# chosed  browser it's set as default browser in gnome
###
blauncher="${INST_BROWSER}"
gconftool-2 -s /desktop/gnome/applications/browser -t string "${blauncher}.desktop"
gconftool-2 -s /apps/panel/objects/browser_launcher/launcher_location -t string "${blauncher}.desktop"

if [ ! -f /usr/local/share/applications/firefox3.desktop ] ; then

# set as epiphany epihany-browser because in applications exsits only epiphany.desktop
	if [ "${launcher}" = "epiphany-browser" ]; then
	launcher="epiphany"
	fi

###
# set homepage as ${DISTRO_URL} in browser
###
set_homepage()
{
case ${launcher} in
	chromium-browser)
		chromium_dir="/usr/local/etc/chromium-browser"
		homepage_ini=`cat ${chromium_dir}/master_preferences | grep homepage | awk '{print $2}'`
		sudo chmod 755 ${chromium_dir}
		sed -i "" "s@${homepage_ini}@\"${DISTRO_URL}\"@" ${chromium_dir}/master_preferences
		sudo chmod 755 ${chromium_dir}
		;;
	epiphany)
		gconftool-2 -s /apps/epiphany/general/homepage -t string "${DISTRO_URL}"
		;;
	firefox3)
		firefox_dir="/home/${USER}/.mozilla"
		if [ ! -d "${firefox_dir}" ] ; then
			mkdir -p ${firefox_dir}/firefox/uwfpw21c.default
		fi
		cat > ${firefox_dir}/firefox/profiles.ini << EOF
[General]
StartWithLastProfile=1

[Profile0]
Name=default
IsRelative=1
Path=uwfpw21c.default
EOF

		;;
	midori)
		midori_dir="/home/${USER}/.config/midori"
		if [ ! -d "${midori_dir}" ] ; then
			mkdir -p ${midori_dir}
		fi
			cat > ${midori_dir}/config << EOF
[settings]
default-encoding=UTF-8
last-window-width=1044

last-window-height=768
last-web-search=1
load-on-startup=MIDORI_STARTUP_HOMEPAGE
preferred-encoding=MIDORI_ENCODING_UNICODE
speed-dial-in-new-tabs=false
location-entry-search=http://search.yahoo.com/search?p=
user-agent=Midori/0.2 (X11; Linux; U; en-us) WebKit/531.2+
EOF
echo "homepage=${DISTRO_URL}" >> ${midori_dir}/config
	;;
esac
}
#set_homepage

###
# add browser launcher in top panel
###
browser_launcher_topanel()
{
pos="1"
right_position="false"
locked_status="true"
if [ "${launcher}" != "epiphany" ] ; then
	add_launcher "${launcher}"
fi
}
browser_launcher_topanel
fi

###
# chose installed mailer from thunderbird and evolution
# chosed mailer  it's set as default in gnome
###
launcher="${MAILER}"
gconftool-2 -s /apps/panel/objects/email_launcher/launcher_location -t string "${launcher}.desktop"
###
# removes  ghostbsd icons from desktop and add them to panel
###

ghostbsd_launchers_topanel()
{
right_position="true"
locked_status="false"
offset="3"
for launcher in ${GHOSTBSD_LAUNCHERS} ; do
add_any_launcher
done
}
ghostbsd_launchers_topanel

applets_launchers_topanel()
{
right_position="true"
locked_status="false"
offset="3"
for launcher in ${APPLETS_LAUNCHERS} ; do
add_any_launcher
done
}
other_launchers_topanel()
{
right_position="false"
locked_status="false"
offset="0"
for launcher in ${OTHER_LAUNCHERS} ; do
if [ `which $launcher` ] ; then
add_any_launcher
fi
done
}
other_launchers_topanel
#add_applet_launcher MixerApplet
