#!/bin/sh
#
# $DesktopBSD$
# $Id: uzip,v 1.4 Saturday, June 20 2015 12:18 Angelescu Ovidiu Exp $
#

# PROVIDE: virtualbox
# REQUIRE: bgfsck
# KEYWORD: nojail

. /etc/rc.subr

name="virtualbox"
start_cmd="virtualbox_start"
stop_cmd="virtualbox_stop"

virtualbox_start() {
# Check if we are in virtualbox to enable vbox-guest-additions
pciconf -lv | grep -q "VirtualBox Graphics"
if  [ $? -eq 0 ] ; then
    /usr/local/etc/rc.d/vboxguest onestart
    /usr/local/etc/rc.d/vboxservice onestart
else
    echo "Real hardware, virtualbox-ose-additions is not installed"
    rm /usr/local/etc/xdj/vboxclient.desktop
fi
}

virtualbox_stop() {
pciconf -lv | grep -q "VirtualBox Graphics"
if  [ $? -eq 0 ] ; then
    /usr/local/etc/rc.d/vboxguest onestop
    /usr/local/etc/rc.d/vboxservice onestop
else
    echo "Real hardware, virtualbox-ose-additions is not installed"
fi
}

load_rc_config $name
run_rc_command "$1"
