#!/bin/sh
# Copyright (c) 2007-2015 The OpenRC Authors.
# See the Authors file at the top-level directory of this distribution and
# https://github.com/OpenRC/openrc/blob/master/AUTHORS
#
# This file is part of OpenRC. It is subject to the license terms in
# the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/OpenRC/openrc/blob/master/LICENSE
# This file may not be copied, modified, propagated, or distributed
#    except according to the terms contained in the LICENSE file.

# If $TERM is not set then assume default of cons25
# This gives us a nice colour boot :)
[ -z "$TERM" -o "$TERM" = "dumb" ] && TERM="cons25" && export TERM

# Handle interrupts
trap : SIGINT
trap "echo 'Boot interrupted'; exit 1" SIGQUIT

if [ -f "/etc/rc.d/cheatcodes" ] ; then
  /etc/rc.d/cheatcodes onestart
  /etc/rc.d/uzip onestart
  /etc/rc.d/unionfs onestart
fi

/sbin/openrc sysinit || exit 1
/etc/rc.d/mountcritlocal onestart
/sbin/openrc boot || exit 1
/sbin/openrc default || exit 1

# Sleep a tick first, which prevents from odd services from crashing
sleep 1

# We don't actually care if rc default worked or not, we should exit 0
# to allow logins
exit 0
