#!/bin/sh

user_dirs()
{
mkdir -p /home/ghostbsd/Desktop
xdg-user-dirs-gtk-update
}

desktop_icons()
{
if [ -e /usr/local/share/applications/ghostbsd-irc.desktop ] ; then
    cp -af /usr/local/share/applications/ghostbsd-irc.desktop \
    /home/ghostbsd/Desktop
    chmod +x /home/ghostbsd/Desktop/ghostbsd-irc.desktop
fi

if [ -e /usr/local/share/applications/gbi.desktop ] ; then
    cp -af /usr/local/share/applications/gbi.desktop \
    /home/ghostbsd/Desktop
    chmod +x /home/ghostbsd/Desktop/gbi.desktop
fi
}

user_dirs
desktop_icons
