#!/bin/sh
#
# $FreeBSD$
# $Id: unionfs,v 1.8 2018/08/28 11:03:11 Angelescu Ovidiu Exp $
#

# PROVIDE: unionfs
# REQUIRE: uzip
# BEFORE:  hostid
# KEYWORD: nojail

. /etc/rc.subr

name="unionfs"
start_cmd="unionfs_start"
stop_cmd=""

unionfs_start() {
    unionsize="$(($(sysctl -n hw.usermem) / 2))b"
    device=$(mdconfig -a -t malloc -s ${unionsize})
    newfs /dev/${device} > /dev/null 2>&1
    mount /dev/${device} /dist/union

    # make dirs with theirs permissions under /dist/union
    mtree -PUer -q -p /dist/union < /etc/mtree/BSD.root.dist > /dev/null 2>&1
    # make dirs with theirs permissions for var and usr
    for dirs in usr var ; do
        mtree -PUer -q -p /dist/union/${dirs} < /etc/mtree/BSD.${dirs}.dist > /dev/null 2>&1
    done
    # make dirs for with theirs permissions under home
    mkdir -p /usr/home
    mtree -PUer -q -p /dist/union/usr/home < /dist/home.dist > /dev/null 2>&1
    # make compat dir under /dist/union
    mkdir -p /dist/union/compat

    # mount uniondirs under /dist/union
    while read uniondir; do
        mount_unionfs -o noatime -o copymode=transparent /dist/union/${uniondir} /${uniondir}
    done < /dist/uniondirs

    # fix permissions for setuid files
    for files in shutdown poweroff mksnap_ffs ping ping6 ; do
        chmod 4554 /sbin/$files
    done
}

load_rc_config $name
run_rc_command "$1"
