#!/bin/sh
cd /home
LS=`ls`
cd - 
for user in ${LS}
do
printf "file:///home/${user}/Documents Documents
file:///home/${user}/Downloads Downloads
file:///home/${user}/Movies Movies
file:///home/${user}/Music Music
file:///home/${user}/Pictures Pictures
" > /home/${user}/.gtk-bookmarks
chown ${user} /home/${user}/.gtk-bookmarks
chmod 755/home/${user}/.gtk-bookmarks

mkdir /home/${user}/Documents
chown ${user} /home/${user}/Documents
chmod 755 /home/${user}/Documents
mkdir /home/${user}/Downloads
chown ${user} /home/${user}/Downloads
chmod 755 /home/${user}/Downloads
mkdir /home/${user}/Movies
chown ${user} /home/${user}/Movies
chmod 755 /home/${user}/Movies
mkdir /home/${user}/Music
chown ${user} /home/${user}/Music
chmod 755 /home/${user}/Music
mkdir /home/${user}/Pictures
chown ${user} /home/${user}/Pictures
chmod 755 /home/${user}/Pictures
done
