name: Project automations

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'master'

# map fields with customized labels
env:
  in_review: In Review

jobs:
  pr_opened:
    name: pr_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.action == 'opened'
    steps:
      - name: Move PR to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          # user: ghostbsd
          organization: ghostbsd
          project_id: 4
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_review }}
